# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Describe your game', max_length=1000, verbose_name='Description')),
                ('launch_year', models.IntegerField(help_text='Which was the year the game was launched?', verbose_name='Launch year')),
            ],
        ),
    ]
