# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 12:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of game genre.', max_length=100, verbose_name='Name')),
                ('description', models.TextField(help_text='Describe the genre.', validators=[django.core.validators.MinLengthValidator(50, 'A genre description must have at least 50 characters!')], verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='information.Genre'),
        ),
    ]
