# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Accepted: png, jpg, jpeg, etc.', upload_to='public/images/', verbose_name='Image')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_image', to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Soundtrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soundtrack', models.FileField(blank=True, help_text='Accepted: mp3, tar.gz, zip, etc', upload_to='public/soundtrack/', verbose_name='Soundtrack')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_soundtrack', to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, help_text='Accepted: mp4, avi, rmvb, etc.', upload_to='public/videos/', verbose_name='Video')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_video', to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
