# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('slider', 'slider'), ('extra', 'extra')], default='slider', help_text='Select the role of this media', max_length=10, verbose_name='Role')),
                ('image', models.ImageField(help_text='Accepted formats: png, jpg, jpeg, etc.', upload_to='images/', verbose_name='Image')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_image', to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Soundtrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('slider', 'slider'), ('extra', 'extra')], default='slider', help_text='Select the role of this media', max_length=10, verbose_name='Role')),
                ('soundtrack', models.FileField(help_text='Accepted formats: mp3, tar.gz, zip, etc', upload_to='soundtrack/', verbose_name='Soundtrack')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_soundtrack', to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('slider', 'slider'), ('extra', 'extra')], default='slider', help_text='Select the role of this media', max_length=10, verbose_name='Role')),
                ('video', models.FileField(help_text='Accepted formats: mp4, avi, rmvb, etc.', upload_to='videos/', verbose_name='Video')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_video', to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
