# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, help_text='Accepted formats: png, jpg, jpeg, etc.', upload_to='public/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='soundtrack',
            field=models.FileField(blank=True, help_text='Accepted formats: mp3, tar.gz, zip, etc', upload_to='public/soundtrack/', verbose_name='Soundtrack'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, help_text='Accepted formats: mp4, avi, rmvb, etc.', upload_to='public/videos/', verbose_name='Video'),
        ),
    ]
