# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 22:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import game.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What's the name of the game?", max_length=100, verbose_name='Game Name')),
                ('game_version', models.CharField(blank=True, help_text="What's the game version?", max_length=20, null=True, validators=[game.validators.validate_version], verbose_name='Game Version')),
                ('official_repository', models.URLField(help_text='What is the official repository for this game?', validators=[django.core.validators.URLValidator()], verbose_name='Official Repository')),
            ],
        ),
    ]
